dependencies:
  - python==3.12
  - poetry==1.8.2
  - git==2.44.0
  - pip==24.0
  - gh==2.45.0
  - pyinstaller==6.11.1
  - pytest==8.1.1
  - pip:
    - numpy==1.26.4 # TODO: check this dependency
    - xarray
    - distributed
    - tzdata
    - pillow
    - pydantic
    - pystac
    - pendulum
    - tqdm
