ARG REGISTRY

FROM ${REGISTRY}mambaorg/micromamba:1.4.1-kinetic

COPY --chown=$MAMBA_USER:$MAMBA_USER Makefile /tmp/Makefile
COPY --chown=$MAMBA_USER:$MAMBA_USER .condarc /tmp/.condarc
COPY --chown=$MAMBA_USER:$MAMBA_USER conda_environment_test.yaml /tmp/conda_environment_test.yaml
COPY --chown=$MAMBA_USER:$MAMBA_USER copernicusmarine /tmp/copernicusmarine
RUN CONDARC=.condarc micromamba install -y -n base make
ARG MAMBA_DOCKERFILE_ACTIVATE=1
COPY --chown=$MAMBA_USER:$MAMBA_USER pip.conf /tmp/pip.conf
RUN /usr/local/bin/_entrypoint.sh make create-test-environment
