MOCK_PRODUCT_GLO = {
    "id": "GLOBAL_ANALYSISFORECAST_PHY_001_024",
    "type": "Collection",
    "stac_version": "1.0.0",
    "stac_extensions": [
        "https://stac-extensions.github.io/scientific/v1.0.0/schema.json"
    ],
    "title": "Global Ocean Physics Analysis and Forecast",
    "description": "The Operational Mercator global ocean analysis and forecast system at 1/12 degree is providing 10 days of 3D global ocean forecasts updated daily. The time series is aggregated in time in order to reach a two full year’s time series sliding window.\n\nThis product includes daily and monthly mean files of temperature, salinity, currents, sea level, mixed layer depth and ice parameters from the top to the bottom over the global ocean. It also includes hourly mean surface fields for sea level height, temperature and currents. The global ocean output files are displayed with a 1/12 degree horizontal resolution with regular longitude/latitude equirectangular projection.\n\n50 vertical levels are ranging from 0 to 5500 meters.\n\nThis product also delivers a special dataset for surface current which also includes wave and tidal drift called SMOC (Surface merged Ocean Current).\n\n**DOI (product):**   \nhttps://doi.org/10.48670/moi-00016",
    "license": "proprietary",
    "providers": [
        {"name": "Mercator Océan International", "roles": ["producer"]},
        {
            "name": "Copernicus Marine Service",
            "roles": ["host", "processor"],
            "url": "https://marine.copernicus.eu",
        },
    ],
    "keywords": [
        "target-application#seaiceforecastingapplication",
        "oceanographic-geographical-features",
        "numerical-model",
        "eastward-sea-water-velocity",
        "northward-sea-water-velocity",
        "sea-surface-wave-stokes-drift-x-velocity",
        "sea-surface-wave-stokes-drift-y-velocity",
        "ocean-mixed-layer-thickness-defined-by-sigma-theta",
        "sea-water-potential-temperature-at-sea-floor",
        "sea-ice-thickness",
        "sea-ice-area-fraction",
        "eastward-sea-ice-velocity",
        "northward-sea-ice-velocity",
        "sea-surface-height-above-geoid",
        "sea-water-pressure-at-sea-floor",
        "surface-snow-thickness",
        "sea-ice-speed",
        "sea-ice-surface-temperature",
        "sea-ice-albedo",
        "age-of-sea-ice",
        "sea-water-salinity",
        "sea-water-potential-temperature",
        "upward-sea-water-velocity",
        "cell-thickness",
        "model-level-number-at-sea-floor",
        "sea-floor-depth-below-geoid",
        "invariant",
        "near-real-time",
        "forecast",
        "marine-resources",
        "coastal-marine-environment",
        "marine-safety",
        "weather-climate-and-seasonal-forecasting",
        "global-ocean",
        "level-4",
        "sea-level",
        "sea-ice-concentration-and/or-thickness",
        "in-situ-ts-profiles",
        "sst",
    ],
    "links": [
        {
            "rel": "root",
            "href": "../catalog.stac.json",
            "title": "Copernicus Marine Data Store",
            "type": "application/json",
        },
        {
            "rel": "parent",
            "href": "../catalog.stac.json",
            "title": "Copernicus Marine Data Store",
            "type": "application/json",
        },
        {
            "rel": "item",
            "href": "cmems_mod_glo_phy-cur_anfc_0.083deg_P1D-m_202211/dataset.stac.json",
            "title": "cmems_mod_glo_phy-cur_anfc_0.083deg_P1D-m_202211",
            "type": "application/json",
        },
        {
            "rel": "item",  # fake item
            "href": "cmems_mod_glo_phy-cur_anfc_0.083deg_P1D-m_206011/dataset.stac.json",
            "title": "cmems_mod_glo_phy-cur_anfc_0.083deg_P1D-m_206011",
            "type": "application/json",
        },
        {
            "rel": "item",  # fake item
            "href": "cmems_obs-oc_glo_bgc-plankton_my_l3-olci-300m_P1D_202211/dataset.stac.json",
            "title": "cmems_obs-oc_glo_bgc-plankton_my_l3-olci-300m_P1D_202211",
            "type": "application/json",
        },
        {
            "rel": "item",
            "href": "cmems_mod_glo_phy-so_anfc_0.083deg_P1D-m_202211/dataset.stac.json",
            "title": "cmems_mod_glo_phy-so_anfc_0.083deg_P1D-m_202211",
            "type": "application/json",
        },
        {
            "rel": "license",
            "href": "https://marine.copernicus.eu/user-corner/service-commitments-and-licence",
            "title": "Copernicus Marine Service Commitments and Licence",
            "type": "text/html",
        },
        {
            "rel": "cite-as",
            "href": "https://doi.org/10.48670/moi-00016",
            "title": "10.48670/moi-00016",
            "type": "text/html",
        },
        {
            "rel": "alternative",
            "href": "https://data.marine.copernicus.eu/product/GLOBAL_ANALYSISFORECAST_PHY_001_024",
            "title": "Product page",
            "type": "text/html",
        },
        {
            "rel": "describedby",
            "href": "https://catalogue.marine.copernicus.eu/documents/QUID/CMEMS-GLO-QUID-001-024.pdf",
            "title": "Quality Information Document",
            "type": "application/pdf",
            "ref": "CMEMS-GLO-QUID-001-024",
            "createdAt": "2016-10-19",
            "updatedAt": "2021-04-19T14:42:00",
        },
        {
            "rel": "describedby",
            "href": "https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-GLO-PUM-001-024.pdf",
            "title": "Product User Manual",
            "type": "application/pdf",
            "ref": "CMEMS-GLO-PUM-001-024",
            "createdAt": "2023-11-30",
            "updatedAt": "2023-11-20T16:08:20.096Z",
        },
        {
            "rel": "describedby",
            "href": "https://catalogue.marine.copernicus.eu/documents/SQO/CMEMS-GLO-SQO-001-024.pdf",
            "title": "Synthesis Quality Overview",
            "type": "application/pdf",
            "ref": "CMEMS-GLO-SQO-001-024",
            "createdAt": "2023-11-30",
            "updatedAt": "2023-11-20T16:09:49.833Z",
        },
    ],
    "extent": {
        "spatial": {"bbox": [[-180, -80, 179.9169921875, 90]]},
        "temporal": {
            "interval": [["2020-11-01T00:00:00Z", "2024-05-02T23:00:00Z"]]
        },
    },
    "assets": {
        "thumbnail": {
            "href": "https://catalogue.marine.copernicus.eu/documents/IMG/GLOBAL-ANALYSIS-FORECAST-PHYS-001-024-c.gif",
            "type": "image/gif",
            "roles": ["thumbnail"],
            "title": "Global Ocean Physics Analysis and Forecast thumbnail",
        }
    },
    "properties": {
        "altId": "2ed3a04a-7dca-4eb0-b0e6-22365a3273a0",
        "creationDate": "2016-10-14",
        "modifiedDate": "2023-11-30",
        "contacts": [
            {
                "name": "Yann Drillet",
                "organisationName": "GLO-MERCATOR-TOULOUSE-FR",
                "responsiblePartyRole": "custodian",
                "email": "yann.drillet@mercator-ocean.fr",
            },
            {
                "name": "Operations",
                "organisationName": "GLO-MERCATOR-TOULOUSE-FR",
                "responsiblePartyRole": "originator",
                "email": "operations@mercator-ocean.fr",
            },
            {
                "name": "GLO Service Desk",
                "organisationName": "GLO-MERCATOR-TOULOUSE-FR",
                "responsiblePartyRole": "pointOfContact",
                "email": "servicedesk.cmems@mercator-ocean.eu",
            },
            {
                "name": "Operations",
                "organisationName": "GLO-NRT-MERCATOR-TOULOUSE-FR",
                "responsiblePartyRole": "resourceProvider",
                "email": "operations@mercator-ocean.fr",
            },
            {
                "name": "Operations",
                "organisationName": "GLO-MERCATOR-TOULOUSE-FR",
                "responsiblePartyRole": "distributor",
                "email": "operations@mercator-ocean.fr",
            },
        ],
        "projection": "Equirectangular",
        "assimilatedData": [
            "Sea Level",
            "Sea Ice Concentration and/or Thickness",
            "In-Situ TS Profiles",
            "SST",
        ],
        "formats": ["NetCDF-3", "NetCDF-4"],
        "updateFrequencies": {"daily": "12:00 UTC", "monthly": None},
        "featureTypes": ["Grid"],
        "indicatorFamilies": [],
        "geoResolution": {
            "row": {"magnitude": 0.083, "units": "degree"},
            "column": {"magnitude": 0.083, "units": "degree"},
        },
        "tempResolutions": ["Hourly", "Daily", "Monthly"],
        "vertLevels": 50,
        "rank": 1000,
        "areas": ["Global Ocean"],
        "times": ["Future", "Present", "Past"],
        "sources": ["Numerical models"],
        "colors": ["White Ocean", "Blue Ocean"],
        "communities": [
            "Polar environment monitoring",
            "Policy & governance",
            "Education",
            "Public health & recreation",
            "Science & innovation",
            "Extremes, hazards & safety",
            "Coastal services",
            "Natural resources & energy",
            "Trade & marine navigation",
        ],
        "processingLevel": "Level 4",
        "mainVariables": [
            "Mixed layer thickness",
            "Salinity",
            "Sea ice",
            "Sea surface height",
            "Temperature",
            "Velocity",
            "Wave",
        ],
        "allVariables": [
            "Age of sea ice (SIAGE)",
            "Cell thickness",
            "Eastward sea ice velocity (SIUV)",
            "Eastward sea water velocity (UV)",
            "Model level number at sea floor",
            "Northward sea ice velocity (SIUV)",
            "Northward sea water velocity (UV)",
            "Ocean mixed layer thickness defined by sigma theta (MLD)",
            "Sea floor depth below geoid",
            "Sea ice albedo (SIALB)",
            "Sea ice area fraction",
            "Sea ice speed",
            "Sea ice surface temperature (IST)",
            "Sea ice thickness (SIT)",
            "Sea surface height above geoid (SSH)",
            "Sea surface wave stokes drift x velocity (UV, VSDXY)",
            "Sea surface wave stokes drift y velocity (UV, VSDXY)",
            "Sea water potential temperature (T)",
            "Sea water potential temperature at sea floor (bottomT)",
            "Sea water pressure at sea floor",
            "Sea water salinity (S)",
            "Surface snow thickness (SNOW)",
            "Upward sea water velocity (UV)",
        ],
        "directives": [],
        "isStaging": False,
        "admp_updated": "2024-04-23T08:52:57.342990Z",
    },
    "sci:doi": "10.48670/moi-00016",
}
