MOCK_STAC_CATALOG = {
    "id": "MDS",
    "type": "Catalog",
    "stac_version": "1.0.0",
    "stac_extensions": [],
    "title": "Copernicus Marine Data Store",
    "description": "Data from the Copernicus Marine Data Store, in Analysis-Ready, Cloud-Optimised (ARCO) format.\n",
    "links": [
        {
            "rel": "self",
            "href": "https://stac.marine.copernicus.eu/metadata/catalog.stac.json",
            "title": "Copernicus Marine Data Store",
            "type": "application/json",
        },
        {
            "rel": "root",
            "href": ".",
            "title": "Copernicus Marine Data Store",
            "type": "application/json",
        },
        {
            "rel": "child",
            "href": "GLOBAL_ANALYSISFORECAST_PHY_001_024/product.stac.json",
            "title": "GLOBAL_ANALYSISFORECAST_PHY_001_024",
            "type": "application/json",
        },
        {
            "rel": "child",
            "href": "NWSHELF_MULTIYEAR_BGC_004_011/product.stac.json",
            "title": "NWSHELF_MULTIYEAR_BGC_004_011",
            "type": "application/json",
        },
        {
            "rel": "child",  # unavailable product
            "href": "UNAVAILABLE_PRODUCT/product.stac.json",
            "title": "UNAVAILABLE_PRODUCT",
            "type": "application/json",
        },
        {
            "rel": "child",  # unavailable product
            "href": "PRODUCT_W_ERRORS/product.stac.json",
            "title": "PRODUCT_W_ERRORS",
            "type": "application/json",
        },
        {
            "rel": "child",
            "href": "DUPLICATE_nwshelf_multiyear_bgc_004_011/product.stac.json",
            "title": "DUPLICATE_nwshelf_multiyear_bgc_004_011",
            "type": "application/json",
        },
        {
            "rel": "child",
            "href": "GLOBAL_ANALYSISFORECAST_PHY_001_024_OTHER/product.stac.json",
            "title": "GLOBAL_ANALYSISFORECAST_PHY_001_024_OTHER",
            "type": "application/json",
        },
        {
            "rel": "describedby",
            "href": "https://documentation.marine.copernicus.eu/QUID/CMEMS-GLO-QUID-001-024..pdf",
            "title": "Quality Information Document",
            "type": "application/pdf",
            "ref": "CMEMS-GLO-QUID-001-024",
            "createdAt": "2016-10-19",
            "updatedAt": "2024-07-26T14:42:36.703Z",
        },
        {
            "rel": "describedby",
            "href": "https://documentation.marine.copernicus.eu/PUM/CMEMS-GLO-PUM-001-024.pdf",
            "title": "Product User Manual",
            "type": "application/pdf",
            "ref": "CMEMS-GLO-PUM-001-024",
            "createdAt": "2023-11-30",
            "updatedAt": "2024-07-26T16:01:37.019Z",
        },
        {
            "rel": "describedby",
            "href": "https://documentation.marine.copernicus.eu/SQO/CMEMS-GLO-SQO-001-024.pdf",
            "title": "Synthesis Quality Overview",
            "type": "application/pdf",
            "ref": "CMEMS-GLO-SQO-001-024",
            "createdAt": "2023-11-30",
            "updatedAt": "2024-07-31T13:26:40.945Z",
        },
    ],
}
