MOCK_PRODUCT_NWSHELF = {
    "id": "NWSHELF_MULTIYEAR_BGC_004_011",
    "type": "Collection",
    "stac_version": "1.0.0",
    "stac_extensions": [
        "https://stac-extensions.github.io/scientific/v1.0.0/schema.json"
    ],
    "title": "Atlantic- European North West Shelf- Ocean Biogeochemistry Reanalysis",
    "description": "**Short  Description:**\n\nThe ocean biogeochemistry reanalysis for the North-West European Shelf is produced using the European Regional Seas Ecosystem Model (ERSEM), coupled online to the forecasting ocean assimilation model at 7 km horizontal resolution, NEMO-NEMOVAR. ERSEM (Butensch&ouml;n et al. 2016) is developed and maintained at Plymouth Marine Laboratory. NEMOVAR system was used to assimilate observations of sea surface chlorophyll concentration from ocean colour satellite data and all the physical variables described in [NWSHELF_MULTIYEAR_PHY_004_009](https://resources.marine.copernicus.eu/?option=com_csw&view=details&product_id=NWSHELF_MULTIYEAR_PHY_004_009). Biogeochemical boundary conditions and river inputs used climatologies; nitrogen deposition at the surface used time-varying data.\n\nThe description of the model and its configuration, including the products validation is provided in the [CMEMS-NWS-QUID-004-011](http://catalogue.marine.copernicus.eu/documents/QUID/CMEMS-NWS-QUID-004-011.pdf). \n\nProducts are provided as monthly and daily 25-hour, de-tided, averages. The datasets available are concentration of chlorophyll, nitrate, phosphate, oxygen, phytoplankton biomass, net primary production, light attenuation coefficient, pH, surface partial pressure of CO2, concentration of diatoms expressed as chlorophyll, concentration of dinoflagellates expressed as chlorophyll, concentration of nanophytoplankton expressed as chlorophyll, concentration of picophytoplankton expressed as chlorophyll in sea water. All, as multi-level variables, are interpolated from the model 51 hybrid s-sigma terrain-following system to 24 standard geopotential depths (z-levels). Grid-points near to the model boundaries are masked. The product is updated biannually,  providing a six-month extension of the time series. See [CMEMS-NWS-PUM-004-009_011](http://resources.marine.copernicus.eu/documents/PUM/CMEMS-NWS-PUM-004-009_011.pdf) for details.\n\n**Associated products:**\n\nThis model is coupled with a hydrodynamic model (NEMO) available as CMEMS product [NWSHELF_MULTIYEAR_PHY_004_009](https://resources.marine.copernicus.eu/?option=com_csw&view=details&product_id=NWSHELF_MULTIYEAR_PHY_004_009).\nAn analysis-forecast product is available from: [NWSHELF_MULTIYEAR_BGC_004_011](https://resources.marine.copernicus.eu/?option=com_csw&view=details&product_id=NWSHELF_MULTIYEAR_BGC_004_011).\n\n**DOI (product):**   \nhttps://doi.org/10.48670/moi-00058\n\n**References:**\n\n* Ciavatta, S., Brewin, R. J. W., Skákala, J., Polimene, L., de Mora, L., Artioli, Y., & Allen, J. I. (2018). [https://doi.org/10.1002/2017JC013490 Assimilation of ocean‐color plankton functional types to improve marine ecosystem simulations]. Journal of Geophysical Research: Oceans, 123, 834–854. https://doi.org/10.1002/2017JC013490\n",
    "license": "proprietary",
    "providers": [
        {"name": "Met Office (UK)", "roles": ["producer"]},
        {
            "name": "Copernicus Marine Service",
            "roles": ["host", "processor"],
            "url": "https://marine.copernicus.eu",
        },
    ],
    "keywords": [
        "oceanographic-geographical-features",
        "numerical-model",
        "mass-concentration-of-picophytoplankton-expressed-as-chlorophyll-in-sea-water",
        "mass-concentration-of-diatoms-expressed-as-chlorophyll-in-sea-water",
        "sea-water-ph-reported-on-total-scale",
        "mole-concentration-of-phosphate-in-sea-water",
        "mole-concentration-of-phytoplankton-expressed-as-carbon-in-sea-water",
        "volume-beam-attenuation-coefficient-of-radiative-flux-in-sea-water",
        "mass-concentration-of-chlorophyll-a-in-sea-water",
        "mole-concentration-of-dissolved-molecular-oxygen-in-sea-water",
        "mole-concentration-of-nitrate-in-sea-water",
        "surface-partial-pressure-of-carbon-dioxide-in-sea-water",
        "net-primary-production-of-biomass-expressed-as-carbon-per-unit-volume-in-sea-water",
        "multi-year",
        "coastal-marine-environment",
        "marine-safety",
        "weather-climate-and-seasonal-forecasting",
        "marine-resources",
        "north-west-shelf-seas",
        "level-4",
        "satellite-chlorophyll",
    ],
    "links": [
        {
            "rel": "root",
            "href": "../catalog.stac.json",
            "title": "Copernicus Marine Data Store",
            "type": "application/json",
        },
        {
            "rel": "parent",
            "href": "../catalog.stac.json",
            "title": "Copernicus Marine Data Store",
            "type": "application/json",
        },
        {
            "rel": "item",
            "href": "cmems_mod_nws_bgc-chl_my_7km-3D_P1D-m_202012/dataset.stac.json",
            "title": "cmems_mod_nws_bgc-chl_my_7km-3D_P1D-m_202012",
            "type": "application/json",
        },
        {
            "rel": "item",  # fake item
            "href": "dataset_w_errors_202012/dataset.stac.json",
            "title": "dataset_w_errors_202012",
            "type": "application/json",
        },
        {
            "rel": "item",
            "href": "cmems_mod_nws_bgc-chl_my_7km-3D_P1M-m_202012/dataset.stac.json",
            "title": "cmems_mod_nws_bgc-chl_my_7km-3D_P1M-m_202012",
            "type": "application/json",
        },
        {
            "rel": "license",
            "href": "https://marine.copernicus.eu/user-corner/service-commitments-and-licence",
            "title": "Copernicus Marine Service Commitments and Licence",
            "type": "text/html",
        },
        {
            "rel": "cite-as",
            "href": "https://doi.org/10.48670/moi-00058",
            "title": "10.48670/moi-00058",
            "type": "text/html",
        },
        {
            "rel": "alternative",
            "href": "https://data.marine.copernicus.eu/product/NWSHELF_MULTIYEAR_BGC_004_011",
            "title": "Product page",
            "type": "text/html",
        },
        {
            "rel": "describedby",
            "href": "https://catalogue.marine.copernicus.eu/documents/QUID/CMEMS-NWS-QUID-004-011.pdf",
            "title": "Quality Information Document",
            "type": "application/pdf",
            "ref": "CMEMS-NWS-QUID-004-011",
            "createdAt": "2019-04-05",
            "updatedAt": "2021-04-19T14:50:02",
        },
        {
            "rel": "describedby",
            "href": "https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-NWS-PUM-004-009-011.pdf",
            "title": "Product User Manual",
            "type": "application/pdf",
            "ref": "CMEMS-NWS-PUM-004-009-011",
            "createdAt": "2013-02-15",
            "updatedAt": "2021-04-19T13:57:32",
        },
        {
            "rel": "describedby",
            "href": "https://catalogue.marine.copernicus.eu/documents/SQO/CMEMS-NWS-SQO-004-011.pdf",
            "title": "Synthesis Quality Overview",
            "type": "application/pdf",
            "ref": "CMEMS-NWS-SQO-004-011",
            "createdAt": "2023-11-30",
            "updatedAt": "2023-12-05T10:53:16.945Z",
        },
    ],
    "extent": {
        "spatial": {
            "bbox": [
                [
                    -19.88888931274414,
                    40.06666946411133,
                    12.999670028686523,
                    65.00125122070312,
                ]
            ]
        },
        "temporal": {
            "interval": [["1993-01-01T00:00:00Z", "2024-01-01T00:00:00Z"]]
        },
    },
    "assets": {
        "thumbnail": {
            "href": "https://catalogue.marine.copernicus.eu/documents/IMG/NWSHELF_MULTIYEAR_BGC_004_011.png",
            "type": "image/png",
            "roles": ["thumbnail"],
            "title": "Atlantic- European North West Shelf- Ocean Biogeochemistry Reanalysis thumbnail",
        }
    },
    "properties": {
        "altId": "29e709a0-1425-4031-8a44-beaa04f7e1f7",
        "creationDate": "2012-08-26",
        "modifiedDate": "2021-04-26",
        "contacts": [
            {
                "name": "NWS Service Desk",
                "organisationName": "NWS-METOFFICE-EXETER-UK (SD)",
                "responsiblePartyRole": "pointOfContact",
                "email": "cmems@metoffice.gov.uk",
            },
            {
                "name": "Andrew Saulter",
                "organisationName": "NWS-METOFFICE-EXETER-UK (WPL)",
                "responsiblePartyRole": "custodian",
                "email": "andrew.saulter@metoffice.gov.uk",
            },
            {
                "name": "Andrew Saulter",
                "organisationName": "NWS-METOFFICE-EXETER-UK (PM)",
                "responsiblePartyRole": "originator",
                "email": "andrew.saulter@metoffice.gov.uk",
            },
            {
                "name": "Service Desk MetOffice",
                "organisationName": "NWS-METOFFICE-EXETER-UK",
                "responsiblePartyRole": "distributor",
                "email": "cmems@metoffice.gov.uk",
            },
            {
                "name": "MetOffice",
                "organisationName": "NWS-METOFFICE-EXETER-UK",
                "responsiblePartyRole": "resourceProvider",
                "email": "cmems@metoffice.gov.uk",
            },
        ],
        "projection": "WGS 84 (EPSG:4326)",
        "assimilatedData": ["Satellite Chlorophyll"],
        "formats": ["NetCDF-4"],
        "updateFrequencies": {"monthly": None, "biannually": None},
        "featureTypes": ["Grid"],
        "indicatorFamilies": [],
        "geoResolution": {
            "row": {"magnitude": 0.111, "units": "degree"},
            "column": {"magnitude": 0.067, "units": "degree"},
        },
        "tempResolutions": ["Daily", "Monthly"],
        "vertLevels": 24,
        "rank": 4700,
        "areas": ["Atlantic: NW European Shelf", "Atlantic: North"],
        "times": ["Past"],
        "sources": ["Numerical models"],
        "colors": ["Green Ocean"],
        "communities": [
            "Conservation & biodiversity",
            "Climate & adaptation",
            "Policy & governance",
            "Science & innovation",
            "Marine food",
        ],
        "processingLevel": "Level 4",
        "mainVariables": [
            "Carbonate system",
            "Nutrients",
            "Optics",
            "Oxygen",
            "Plankton",
        ],
        "allVariables": [
            "Mass concentration of chlorophyll a in sea water (CHL)",
            "Mass concentration of diatoms expressed as chlorophyll in sea water (CHL)",
            "Mass concentration of picophytoplankton expressed as chlorophyll in sea water (CHL)",
            "Mole concentration of dissolved molecular oxygen in sea water (O2)",
            "Mole concentration of nitrate in sea water (NO3)",
            "Mole concentration of phosphate in sea water (PO4)",
            "Mole concentration of phytoplankton expressed as carbon in sea water (PHYC)",
            "Net primary production of biomass expressed as carbon per unit volume in sea water (PP)",
            "Sea water ph reported on total scale (pH)",
            "Surface partial pressure of carbon dioxide in sea water (spCO2)",
            "Volume beam attenuation coefficient of radiative flux in sea water (KD)",
        ],
        "directives": [
            "Marine Strategy Framework Directive (MSFD)",
            "Water Framework Directive (WFD)",
        ],
        "crs": "EPSG:4326",
        "isStaging": False,
        "admp_updated": "2024-03-27T11:38:55.250219Z",
    },
    "sci:doi": "10.48670/moi-00058",
}
