name: Create Binaries Windows

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.5.6-0'
        micromamba-binary-path: ${{ runner.temp }}\Scripts\micromamba.exe
        environment-file: conda_environment_binary.yaml
        environment-name: copernicusmarine-binary
        condarc-file: .condarc
        cache-environment: true
        post-cleanup: 'all'

    - name: Build with PyInstaller
      shell: bash -el {0}
      run: |
        make run-using-pyinstaller-windows-latest

    - name: Set VERSION environment variable
      id: set-version
      shell: bash -el {0}
      run: echo "VERSION=$(poetry version --short)" >> $GITHUB_OUTPUT

    - name: Upload binaries to windows
      shell: bash -el {0}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
          gh release upload v${{steps.set-version.outputs.VERSION}} dist/copernicusmarine.exe#copernicusmarine-binary-windows-for-v${{steps.set-version.outputs.VERSION}}
