name: Actions Runner Controller Demo
on:
  pull_request:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: lobelia-cf
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
