name: Test large downloads

on:
  pull_request_target:
    branches:
      - "main"
  schedule:
    - cron: '0 0 * * 6'

jobs:
  tests:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0'
          micromamba-binary-path: ${{ runner.temp }}\Scripts\micromamba.exe
          environment-file: conda_environment_binary.yaml
          environment-name: copernicusmarine-binary
          condarc-file: .condarc
          cache-environment: true
          post-cleanup: 'all'

      - name: Test large downloads
        env:
          COPERNICUSMARINE_SERVICE_USERNAME: ${{ secrets.COPERNICUSMARINE_SERVICE_USERNAME }}
          COPERNICUSMARINE_SERVICE_PASSWORD: ${{ secrets.COPERNICUSMARINE_SERVICE_PASSWORD }}
        run: make run-large-downloads
        shell: bash -el {0}
