name: Create Windows Binary
on:
  push:
    branches:
       - main
       - 'pre-releases/**'
  pull_request:
    branches:
       - copernicusmarine-toolbox-v2
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        make build-and-prepare-for-binary-windows-latest
    - name: Set Version
      id: set-version
      run: |
        pip install poetry
        echo "VERSION=$(poetry version --short)" >> $GITHUB_ENV

    - name: Build with PyInstaller
      run: |
        make run-using-pyinstaller-windows-latest
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: windows-binary
        path: dist/copernicus_marine.exe
        overwrite: true

    - name: Gitod binary
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload "v2.0.0a1" dist/copernicus_marine.exe
